In [28]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [29]:

dataset = [['Milk','Onion', 'Bread', 'Kidney Beans','Eggs','Bread'],
           ['Fish','Onion','Bread','Kidney Beans','Eggs','Bread'],
           ['Milk', 'Apples', 'Kidney Beans’, ‘Eggs'],
           ['Milk', 'Sugar', 'Tea Leaves', 'Kidney Beans', 'Bread'],
           ['Tea Leaves','Onion','Kidney Beans', 'Ice cream', 'Eggs'],]

In [30]:
from apyori import apriori

transacts = []
for i in range(len(dataset)):
    transacts.append([dataset[i][j] for j in range(len(dataset[i]))])

rule = apriori(transactions = transacts, min_support = 0.03, min_confidence = 0.02, min_lift = 3, min_length = 2, max_length = 1000)
results=list(rule)

In [31]:
def inspect(results):
    lhs         = [tuple(result[2][0][0])[0] for result in results]
    rhs         = [tuple(result[2][0][1])[0] for result in results]
    support    = [result[1] for result in results]
    confidence = [result[2][0][2] for result in results]
    lift       = [result[2][0][3] for result in results]
    return list(zip(lhs, rhs, support, confidence, lift))
output_DataFrame = pd.DataFrame(inspect(results), columns = ['Left_Hand_Side', 'Right_Hand_Side', 'Support', 'Confidence', 'Lift'])

In [32]:
output_DataFrame

   Left_Hand_Side       Right_Hand_Side  Support  Confidence  Lift
0          Apples  Kidney Beans’, ‘Eggs      0.2         1.0   5.0
1          Apples                  Milk      0.2         1.0   5.0
2           Sugar            Tea Leaves      0.2         1.0   5.0
3       Ice cream            Tea Leaves      0.2         1.0   5.0
4       Ice cream                 Onion      0.2         1.0   5.0
5           Sugar            Tea Leaves      0.2         1.0   5.0
6           Sugar            Tea Leaves      0.2         1.0   5.0
7           Sugar            Tea Leaves      0.2         1.0   5.0
8       Ice cream            Tea Leaves      0.2         1.0   5.0
9       Ice cream                 Onion      0.2         1.0   5.0
10      Ice cream                 Onion      0.2         1.0   5.0
11          Sugar            Tea Leaves      0.2         1.0   5.0
12          Sugar            Tea Leaves      0.2         1.0   5.0
13      Ice cream                 Onion      0.2         1.0   5.0